### ISSUE TITLE
Order Price is -1

### ISSUE THREAD

**Issue by handshou** [IS3106-T07/Qoodie#21]
## Order Price is -1
**Endpoint** `/Resource/customers/orders`

Not sure why the order price is -1, when the dish price and dish amount is okay!

> Amount: 10
> Dish price: $9.29
> Order price: -$1 (uninitialised)

See: Line 5 below.
``` Json
// Result of endpoint
[
    {
        "id": 38,
        ...,
        "price": -1,
        "customer": {
            "id": 36,
            "email": "alice@gmail.com",
            ...,
            "customerOrders": null
        },
        "orderDishes": [
            {
                "id": 37,
                "dish": {
                    "id": 34,
                    "name": "fiery chicken",
                    "isAvailable": true,
                    "price": 9.285709420704054,
                    ...,
                },
                "amount": 10,
                "customerOrder": null
            }
        ],
        "customerOrderType": {
            "id": 13,
            "name": "IN BASKET",
            "customerOrders": null
        }
    }
]
```

Lines from `CustomerOrder.java` below.
``` Java
// uninitialised price
public class CustomerOrder implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Temporal(TemporalType.TIME)
    private Date created;
    @Temporal(TemporalType.TIME)
    private Date lastUpdate;
    Double price = -1.0;
    ...
```

Seems like CustomerOrder price is uninitialised. Didn't investigate why it is so.

## Affects frontend render
<img width="193" alt="screenshot 2018-11-14 at 3 25 35 am" src="https://user-images.githubusercontent.com/12982599/48437710-114e9d00-e7bd-11e8-98ca-7dc6d7092bec.png">

**Issue**: shows minus ' - ' sign and a line-break

**Comment by murmurise** [comment]
it is -1 coz it not paid yet. the price field will only be filled in if the payment is made(as in, finalised). this is is case the vendor changed the price of the dish. 
so before it is purchased, the price should be calculated by the orderitems @handshou

**Comment by handshou** [comment]
hmm, ok, is orderItems is vendor’s feature?

________________________________

**Comment by handshou** [comment]
Ok, nice, working as intended.
Calculation must be done on frontend and an API call made to backend to update the order's price.
